- autodmg_cache_builder/autodmg_cache_build.py
This adds two things:
* If basic auth has been specified, it is used to download the icons
* Icons will be added for optional installs, managed updates and removals as well as managed installs.
> Icons for all

- autodmg_cache_builder/README.md
- autodmg_cache_builder/autodmg_cache_build.py
- autodmg_cache_builder/autodmg_utility.py
This PR allows you to:
* Specify an arbitrary location to move the resulting DMG (to allow for moving to locations used by other tools, not just DeployStudio)
* Skip the applying of Apple Updates (useful for when there is a new OS X Installer, but no update to AutoDMG's updates yet)
> Disable updates and move file

- autodmg_cache_builder/autodmg_cache_build.py
This respects the current settings but allows mobileconfigs to be installed in the image.
> ADCB: allow mobileconfigs to install

- autodmg_cache_builder/autodmg_cache_build.py
FALSE is better than referenced before assignment
> fix ad⚡️cb noicons handling

- chef/cookbooks/cpe_munki/README.md
- chef/cookbooks/cpe_munki/resources/cpe_munki_local.rb
When you remove an app from Munki using managed_uninstalls, this logic
will now also remove the app from the selfservemanifest (optional installs).
In addition, we do a sanity check to verify that Munki is actually installed.
> Remove managed_uninstall apps from optional installs

- chef/cookbooks/cpe_init/recipes/company_init.rb
Cannot have munki install true until we provide everything needed for it to actually work. This can be changed back when it is functional out of the box. (Currently it is completely broken).
> Set munki install and configure false for quickstart json

- chef/cookbooks/cpe_munki/resources/cpe_munki_local.rb
This is causing travisci to blow up for every PR.
> Disable a warning that is silly for our use case

- chef/cookbooks/cpe_preferencepanes/README.md
- chef/cookbooks/cpe_preferencepanes/resources/default.rb
Make sure if nothing is passed for one or the other payloads, it uses an empty array instead. This prevents system prefs from getting cranky.
> Updated to handle prefs better in the case one array is missing

- chef/cookbooks/cpe_munki/resources/cpe_munki_local.rb
Moves the /opt/facebook/munki_catalog_items.json file to a path that should exist by default on a Munki installs, /Library/Managed Installs/
> Move munki_catalog_items to /Library/Managed Installs/

- adobe_tools/README.md
- use backticks for file and class names
This is just a minor formatting suggestion that I hope will help with readability. I've submitted the CLA.
> Markdown formatting

- chef/cookbooks/cpe_chrome/resources/cpe_chrome.rb
Found a bug when looking at rewriting some cookbooks.
> fix Chrome canary to not manage Safari

- chef/cookbooks/cpe_remote/README.md
This resource will prefix https so don't include it in the base_url or
errors will occur.
> fix: Update cpe_remote README

- chef/cookbooks/cpe_remote/resources/file.rb
Sometimes the group lookup in the cpe_remote_file resource fails using the Etc module.  This diff uses a begin/rescue clause in the group assignment to catch outliers and edge cases.  This change has been running for a few months at Facebook  and resolved a few edge case errors with this resource.
> fix cpe_remote_file

- chef/tools/chef_bootstrap.py
This change is to update the Ohai syntax to work with latest Chef clients.
We found that until these changes were made, chef-client version 13.x did not respect the Ohai settings, specifically the `disabled_plugins` which caused our systems to experience the `:Passwd` bug where the system freezes. After making this change, the plugin is now actually disabled during a chef-client run.
See syntax here as well: https://docs.chef.io/ohai.html under the "Ohai Settings in client.rb"
> Changing Ohai syntax

- chef/cookbooks/cpe_munki/resources/cpe_munki_config.rb
When ruby parses the attributes for preferences it doesn't strip the
`nil` values and instead will write the value as <data> inside the
profile.
Example:
```
<key>RecoveryKeyFile</key>
<data>
BAgw
</data>
```
This will render as `<040830>` inside of System Preferences.
This causes Munki to use this malformed data and is unable to
interpret it properly causing https://github.com/munki/munki/issues/799.
Munki can be more resilient to bad data but Chef shouldn't create the bad
data in the first place.
> fix: Munki prefs shouldn't have ruby nils

- chef/cookbooks/cpe_init/metadata.rb
- chef/cookbooks/cpe_init/recipes/mac_os_x_init.rb
- chef/cookbooks/cpe_utils/libraries/node_functions.rb
- chef/cookbooks/cpe_utils/libraries/registry_functions.rb
- chef/cookbooks/cpe_win_telemetry/README.md
- chef/cookbooks/cpe_win_telemetry/attributes/defaults.rb
- chef/cookbooks/cpe_win_telemetry/metadata.rb
- chef/cookbooks/cpe_win_telemetry/recipes/default.rb
- chef/cookbooks/cpe_win_telemetry/resources/cpe_win_telemetry.rb
API cookbook that will manage the windows telemetry settings on Windows nodes.  Also adds the registry_functions in cpe_utils.
> Add API cookbook to manage windows telemetry settings

- chef/tools/chef_bootstrap.py
Noticed bootstrap was failing on 10.13 for the CLI Tools portion, so I decided to update the receipts:
Before
```
Checking for OS X CLI Tools... not installed.
Software update failed!
```
After:
```
Checking for OS X CLI Tools... installed.
Setting up Chef config files.
Checking for Chef install...
Obtaining Chef...
Downloading from Chef directly... downloaded from Chef.io.
Installing Chef.
installer: Package name is Chef Client
installer: Installing at base path /
installer: The install was successful.
Finished installing Chef.
Running client, saving output to /Library/Chef/Logs/bootstrap.log
Running client, saving output to /Library/Chef/Logs/bootstrap.log
Running client, saving output to /Library/Chef/Logs/bootstrap.log
Bootstrap complete!
```
> Updating chef_bootstrap.py for 10.13

- chef/cookbooks/cpe_remote/resources/pkg.rb
Per the documentation here, I updated the use of property names in the pkg.rb resource: https://docs.chef.io/deprecations_namespace_collisions.html
Before this change, upon running a recipe that used the cpe_remote_pkg resource, you would receive deprecation notices like so:
```
Deprecated features used!
rename mpkg to current_resource.mpkg at 1 location:
- ../chef/chef-repo/.chef/local-mode-cache/cache/cookbooks/cpe_remote/resources/pkg.rb:70:in `block (2 levels) in class_from_file'
See https://docs.chef.io/deprecations_namespace_collisions.html for further details.
rename app to new_resource.app at 1 location:
- ../chef/chef-repo/.chef/local-mode-cache/cache/cookbooks/cpe_remote/resources/pkg.rb:80:in `block (2 levels) in class_from_file'
See …
```
> Updating property_names in actions to keep in line with chef deprecation policies

- chef/tools/chef_bootstrap.py
The Command line tools were renamed to be more in line with 10.12 and 10.13, so 10.11 machines would fail to download the Command Line Tools (I know... I'm ashamed we have 10.11 machines too 👎  ). The tools are now called "Command Line Tools (macOS El Capitan version 10.11) for Xcode."
> Updating desired_platform string for 10.11

- chef/cookbooks/cpe_utils/README.md
- chef/cookbooks/cpe_utils/libraries/node_functions.rb
This allows you to do cool things like manage launchdaemons/agents dynamically depending on the version of software installed.
I am using this for Munki 3.2 -> 3.3 migration.
> Min max package, update readme and add additional functionality for virtual_type

- chef/cookbooks/cpe_safari/resources/cpe_safari.rb
As discovered [here](https://gist.github.com/erikng/97d9910ca16e86c720e667bbce6850a2), Apple has now prevented the Safari payload type from being installed via root, without further admin input.
This is more than likely a reaction to [this](https://blog.malwarebytes.com/threat-analysis/2018/04/new-crossrider-variant-installs-configuration-profiles-on-macs/). 
I have tested that MC X profile payloads are not impacted by this (for now), so I think we should unfortunately revert back to MC X.
> revert cpe_safari for 10.13.4 changes

- chef/cookbooks/cpe_office/README.md
- chef/cookbooks/cpe_office/attributes/default.rb
- chef/cookbooks/cpe_office/resources/darwin.rb
This PR will extend `cpe_office` to also manage keys for the `com.microsoft.autoupdate2` (Microsoft Autoupdate 2.0) preference domain.
> Add MAU pref domain functionality

- .travis.yml
Upgrading the version of ruby used for tests. Seems a good amount of gems were updated since the fix went out. 
I'm not too sure if updating the ruby version will lint for chef 14, but I'm making the change to see. I do understand the cookbooks in this repo are not 14 ready.
> Update .travis.yml for Ruby 2.4.1

- chef/cookbooks/cpe_utils/libraries/cpe_utils.rb
This helper allows you to speciufy root_user and root_group cross-platform and always get the correct thing.
> Add cpe_utils helpers for root owner and group

- chef/cookbooks/cpe_utils/libraries/node_functions.rb
Replaces `s art_date:` with `start_date` on L208 of `nodefunctions.rb`
> Typo: 's art_date' > 'start_date'

- chef/cookbooks/cpe_pathsd/files/default/paths
- chef/cookbooks/cpe_pathsd/metadata.rb
- chef/cookbooks/cpe_pathsd/recipes/darwin.rb
- chef/cookbooks/cpe_pathsd/recipes/linux.rb
- chef/cookbooks/cpe_pathsd/templates/default/cpe_pathsd
- chef/cookbooks/cpe_pathsd/templates/default/profile.d_paths.erb
This updates `cpe_pathsd` to move the existing resources to a Darwin-specific recipe and ensures a sane default path is always enforced.
Also introduce a Linux recipe. The API is the same on both platforms, but on Linux the result is only compatible with Bourne-compatible POSIX shells (`bash`, `zsh`, etc.).
On both Darwin and Linux, remove any duplicate path entries that may have been added to the list.
> Update cpe_pathsd to work on Linux

- chef/cookbooks/cpe_remote/resources/zip.rb
Fixes all `new_resource.PROPERTY` calls so chef 14 is happy.
Tested on macOS, but should also fix it for Linux/Windows.
> Update cpe_remote_zip for chef14

- chef/cookbooks/cpe_powermanagement/README.md
The readme for `cpe_powermanagement` references two different keys for the 'plugged in' power state. This PR replaces all references to the invalid key `AC` with the correct `ACPower` key.
CLA has been completed.
> Fixed typo in `cpe_powermanagement` readme

- chef/cookbooks/cpe_adobe_flash/README.md
- chef/cookbooks/cpe_adobe_flash/attributes/default.rb
This PR, if merged, will append three new configurable options to the cookbook (`EventJitterMicroseconds`, `TimerJitterMicroseconds`, `InsecureJitterDisabledDomain`). These options are relating to mitigation of the Spectre/Meltdown CVE's (and other similar attack styles).
The documentation for these options can be found in the Adobe Flash Player Administration Guide [1] on pages 43 and 44.
[1] https://www.adobe.com/content/dam/acom/en/devnet/flashplayer/articles/flash_player_admin_guide/pdf/flash_player_32_0_admin_guide.pdf#G7.3058663
> cpe_adobe_flash: +3x "Jitter"-related options

- chef/cookbooks/cpe_adobe_flash/README.md
- tests/run_foodcritic.rb
1. Commit (e38ea88) in this PR fixes bad commit (6113420) from PR #205 whereby I erroneously removed a line from `README.md`.
2.  Additionally, I noticed today that PR #205 had actually [failed its Travis tests](https://travis-ci.org/facebook/IT-CPE/builds/506490205?utm_source=github_status&utm_medium=notification) for violating 5 distinct rules:
```
FC066: Ensure chef_version is set in metadata: chef/cookbooks/cpe_adobe_flash/metadata.rb:1
FC067: Ensure at least one platform supported in metadata: chef/cookbooks/cpe_adobe_flash/metadata.rb:1
FC069: Ensure standardized license defined in metadata: chef/cookbooks/cpe_adobe_flash/metadata.rb:1
FC071: Missing LICENSE file: chef/cookbooks/cpe_adobe_flash/LICENSE:1
FC078: Ensure cookbook shared under an OSI-approved open source license: …
```
> Fix prior README typo; +5 F.C. rule exclusions

- itchef/cookbooks/cpe_munki/README.md
- itchef/cookbooks/cpe_munki/attributes/default.rb
- itchef/cookbooks/cpe_munki/metadata.rb
- itchef/cookbooks/cpe_munki/recipes/default.rb
- itchef/cookbooks/cpe_munki/resources/cpe_munki_config.rb
- itchef/cookbooks/cpe_munki/resources/cpe_munki_install.rb
- itchef/cookbooks/cpe_munki/resources/cpe_munki_local.rb
The internal and external repositories are out of sync. This attempts to brings them back in sync by patching the GitHub repository. Please carefully review this patch. You must disable ShipIt for your project in order to merge this pull request. DO NOT IMPORT this pull request. Instead, merge it directly on GitHub using the MERGE BUTTON. Re-enable ShipIt after merging.
> Re-sync with internal repository
