facebook/IT-CPE

- autodmg_cache_builder/autodmg_cache_build.py
Auto-adds mobileconfigs it finds to exceptions, fixes caching on-image, and adds check for path to AutoDMG.
> Enable hardcoding of mobileconfigs to excepts, tweaks

- chef/tools/profile_to_hash.rb
> Updated to warn if required gems were not installed

- chef/cookbooks/cpe_init/README.md
- chef/cookbooks/cpe_init/recipes/company_init.rb
- chef/cookbooks/cpe_init/recipes/mac_os_x_init.rb
> Cpe init readme

- chef/cookbooks/cpe_bluetooth/README.md
- chef/cookbooks/cpe_launchd/README.md
- chef/cookbooks/cpe_profiles/README.md
- chef/cookbooks/cpe_safari/README.md
- chef/cookbooks/cpe_screensaver/README.md
> Clarified prefix usage for profile api cookbooks

- chef/cookbooks/cpe_chocolatey/README.md
- chef/cookbooks/cpe_chocolatey/attributes/default.rb
- chef/cookbooks/cpe_chocolatey/files/default/choco-run.ps1
- chef/cookbooks/cpe_chocolatey/files/default/chocolatey.config
- chef/cookbooks/cpe_chocolatey/metadata.rb
- chef/cookbooks/cpe_chocolatey/recipes/configure.rb
- chef/cookbooks/cpe_chocolatey/recipes/default.rb
- chef/cookbooks/cpe_chocolatey/recipes/required_apps.rb
This is a cookbook that will install chocolatey and setup a scheduled task to run every 30min to update/install required packages.
> Add cpe_chocolatey cookbook

- chef/README.md
- chef/quickstart.json
Readme to get started with our chef cookbooks.
> Added quickstart readme

- autodmg_cache_builder/autodmg_cache_build.py
This lets you actually specify a log level.
> Add type to log level option

- chef/cookbooks/osx_server/README.md
- chef/cookbooks/osx_server/recipes/default.rb
included recipes were not respected. Also added readme about the dependency.
> fix cookbook: osx_server

- chef/cookbooks/cpe_bluetooth/recipes/default.rb
- chef/cookbooks/cpe_bluetooth/resources/cpe_bluetooth.rb
> Bluetooth as a resource

- chef/cookbooks/cpe_desktop/README.md
- chef/cookbooks/cpe_desktop/attributes/default.rb
- chef/cookbooks/cpe_desktop/metadata.rb
- chef/cookbooks/cpe_desktop/recipes/default.rb
- chef/cookbooks/cpe_desktop/resources/cpe_desktop.rb
- chef/cookbooks/cpe_init/metadata.rb
- chef/cookbooks/cpe_init/recipes/mac_os_x_init.rb
Another one for reception areas.... :)
> Added cpe_desktop cookbook

- chef/cookbooks/cpe_powermanagement/resources/cpe_powermanagement.rb
Fixed this issue in our internal code repo. Pushing to public.
> [cpe_powermanagement] Adding default value for battery lookup

- README.md
Has moved from Kens to its own GH org
> Invalid URL for requests module

- chef/cookbooks/cpe_screensaver/resources/cpe_screensaver.rb
CPE Screensaver now only runs if set.
> CPE Screensaver now only runs if set.

- README.md
We don't have to have a minimum version, but we should explain this is running against the latest major OS releases.
> Mention OS version support in README

- chef/cookbooks/cpe_chrome/README.md
- chef/cookbooks/cpe_chrome/attributes/default.rb
- chef/cookbooks/cpe_chrome/metadata.rb
- chef/cookbooks/cpe_chrome/recipes/darwin_chrome.rb
- chef/cookbooks/cpe_chrome/recipes/linux_chrome.rb
- chef/cookbooks/cpe_chrome/recipes/windows_chrome.rb
- chef/cookbooks/cpe_chrome/resources/cpe_chrome.rb
- chef/cookbooks/cpe_chrome/resources/cpe_chrome_cleanup.rb
- chef/cookbooks/cpe_chrome/spec/spec_helper.rb
Cpe Chrome to check if installed as attr
> Cpe Chrome to check if installed as attr

- chef/cookbooks/cpe_logger/README.md
- chef/cookbooks/cpe_logger/libraries/cpe_log.rb
- chef/cookbooks/cpe_logger/metadata.rb
- chef/cookbooks/cpe_logger/recipes/default.rb
- chef/cookbooks/cpe_logger/spec/cpe_log_spec.rb
> Cpe logger

- autodmg_cache_builder/autodmg_cache_build.py
- autodmg_cache_builder/autodmg_utility.py
- autodmg_cache_builder/except_adds.json
Update from internal copy of ADCB
> Update from internal

- chef/cookbooks/cpe_launchd/README.md
> Broken Link

- chef/cookbooks/cpe_remote/libraries/helpers.rb
- chef/cookbooks/cpe_remote/resources/file.rb
to fix : https://github.com/facebook/IT-CPE/issues/160
> [cpe_remote] Separating internal library out of resource

- chef/cookbooks/cpe_remote/resources/pkg.rb
pkg_url was not being respected if it was provided
> Updating cpe_remote_pkg

- chef/cookbooks/cpe_utils/libraries/node_functions.rb
This is a re-do of https://github.com/facebook/IT-CPE/pull/89
It properly chomps the string vs using string manipulation via shell. If we can get this merged, I can send another PR for the things we discussed earlier.
> virtual_macos_type function

- chef/cookbooks/cpe_munki/README.md
- chef/cookbooks/cpe_munki/resources/cpe_munki_install.rb
I like my cpe_remote pkg repo sorted. This helps :)
> allow overriding munki pkg name

- chef/cookbooks/cpe_choco/resources/cpe_choco_apps.rb
- chef/cookbooks/cpe_utils/libraries/node_functions.rb
- chef/cookbooks/cpe_utils/libraries/registry_functions.rb
As promised...
I think I got all the unnecessary ones.
> Remove unnecessary return statements.

- chef/cookbooks/cpe_utils/libraries/node_functions.rb
- chef/cookbooks/cpe_utils/libraries/osquery.rb
Sync over new node functions since last update. Also added osquery.rb for getting info back from osquery.
> update node functions

- chef/cookbooks/cpe_utils/README.md
Adds references to new OS check functions which have been added to `node_functions.rb`.
> Add new OS checks to README

- chef/cookbooks/cpe_user_customizations/recipes/default.rb
this will make it so erik == ERIK == Erik in case a user has an uppercase in their username
> allow permutations of node.console_user

- chef/cookbooks/cpe_utils/libraries/node_functions.rb
> Add ubuntu support to node.console_user

- chef/cookbooks/cpe_powermanagement/resources/cpe_powermanagement.rb
@nmcspadden Please carefully examine this to ensure it meets your standards and then forget about it and ignore it for six months. 😝
> cpe_powermanagement: Hash#keys.each to Hash#each_key

- itchef/cookbooks/cpe_applocker/README.md
- itchef/cookbooks/cpe_applocker/attributes/default.rb
- itchef/cookbooks/cpe_applocker/configurations/default_allow_publisher.rb
- itchef/cookbooks/cpe_applocker/configurations/default_deny_hash.rb
- itchef/cookbooks/cpe_applocker/libraries/applocker_helpers.rb
- itchef/cookbooks/cpe_applocker/metadata.rb
- itchef/cookbooks/cpe_applocker/recipes/default.rb
- itchef/cookbooks/cpe_applocker/resources/cpe_applocker.rb
- itchef/cookbooks/cpe_applocker/spec/default_spec.rb
The internal and external repositories are out of sync. This attempts to brings them back in sync by patching the GitHub repository. Please carefully review this patch. You must disable ShipIt for your project in order to merge this pull request. DO NOT IMPORT this pull request. Instead, merge it directly on GitHub using the MERGE BUTTON. Re-enable ShipIt after merging.
> Re-sync with internal repository
